### PR TITLE
updates

### PR DESCRIPTION
**Pull request by shannonpileggi**

### CODE REVIEW

**Comment by shannonpileggi** [comment]
@ddsjoberg would you be willing to review this prior to pushing live? does this better reflect the current state of `gtsummary`? I'm open to other suggestions, or collaborating on a separate post about gtsummary + labelled data if you think there are questions still out there unanswered.

**Comment by ddsjoberg** [comment]
> @ddsjoberg would you be willing to review this prior to pushing live? does this better reflect the current state of `gtsummary`? I'm open to other suggestions, or collaborating on a separate post about gtsummary + labelled data if you think there are questions still out there unanswered.
> 
> You can preview the post [here](https://deploy-preview-11--flamboyant-mccarthy-854a9b.netlify.app/posts/2020-12-23-leveraging-labelled-data-in-r/).

@shannonpileggi thank you for the opportunity to review! I just submitted a lil' PR.

I think another short blog post with gtsummary+labelled data would be great! In the dev version of the gtsummary website, I added a section for Additional Resources, and we can add a link to the post there!
https://www.danieldsjoberg.com/gtsummary/dev/index.html#additional-resources

**Comment by shannonpileggi** [comment]
> @shannonpileggi thank you for the opportunity to review! I just submitted a lil' PR.

Thanks! I always appreciiate your keen eye.
 
> I think another short blog post with gtsummary+labelled data would be great! In the dev version of the gtsummary website, I added a section for Additional Resources, and we can add a link to the post there!
> https://www.danieldsjoberg.com/gtsummary/dev/index.html#additional-resources

Ok! Do you have any thoughts on what common points of confusion are? Are there issues not addressed in [Polished summary tables in R with gtsummary](https://www.pipinghotdata.com/posts/2021-07-14-polished-summary-tables-in-r-with-gtsummary/), or would you prefer something more targeted to labelled data + gtsummary, rather than a general overview?

**Comment by ddsjoberg** [comment]
Ahhh, this is a very good question. Your post already covers most everything! I don't use labelled data, so I am not sure if anything is missing. The one thing that sticks out (and I am not even sure this applies to labelled data), is continuous variables with special coded missing values. For example, if a questionnaire asks about for your age, and our data set has ages along with -99 for missing...I am not sure how to "unlabel" this data for preparation to pass to gtsummary? LIkely doesn't need to be a full on blog post, since most of it is covered already?

**Comment by shannonpileggi** [comment]
@ddsjoberg Hm - that is something I haven't yet encountered. My labelled data comes through programmed surveys which use a fairly consistent process, and the continuous variables come in as integer/double, whatever, not as labelled objects. Have you seen others struggle with this? I can also ask around about more labelled data in the wild 😀

**Comment by ddsjoberg** [comment]
> @ddsjoberg Hm - that is something I haven't yet encountered. My labelled data comes through programmed surveys which use a fairly consistent process, and the continuous variables come in as integer/double, whatever, not as labelled objects. Have you seen others struggle with this? I can also ask around about more labelled data in the wild 😀

OH no worries, please ignore me 😆 I don't use labelled data and don't know what I am talking about! Thank you so much for updating the RView post and blog post! The rate of updates in gtsummary has slowed dramatically in the last 6 months (and I am so happy about that!), so hopefully going forward everything will be consistent!

**Comment by shannonpileggi** [comment]
Ok, that sounds good, I'm all ears if you have ideas for additional tutorials! 😀

**Pull request merged**
