### PR TITLE
r config post

### PR DESCRIPTION
**Pull request by shannonpileggi**

### CODE REVIEW

**Comment by jennybc** [comment]
Very helpful post! I'm just noting two observations I had while reading it.

---

Re: home directory

It's tricky to know how to label the different notions of home directory. I don't necessarily have a specific suggestion, but I'm not sure how standard or un-controversial "User home directory" vs. "R home directory" is. The sad fact is, on Windows, reasonable applications can disagree about this.

If you're going to get into env vars related to home directory, you might want to also include the ones consulted by fs (<https://fs.r-lib.org/reference/path_expand.html>): `USERPROFILE`, `HOMEDRIVE`, `HOMEPATH`.

---

I think devtools's "dev_mode" is almost a thing of the past. FWIW I don't use it and I don't know of anyone on the tidyverse/r-lib team that does. I don't really hear of people using it these days.

The way I think of my libraries is that the default state is I've got all sorts of things installed at "CRAN or later" versions. And, in general, this works for me. Any pain I experience is mostly productive, in terms of either learning about problems in in-development packages or allowing me to file a helpful bug report before something gets released.

For projects that truly require a more disciplined approach, I would use renv.

So there's really no unmet need which "dev mode" helps with. I guess I basically live in "dev mode" and turn to something like renv when that is too loosey-goosey.

**Comment by shannonpileggi** [comment]
Thank you very much for the feedback @jennybc! I removed the dev mode section and added in the additional env variables.

**Comment by jennybc** [comment]
Thinking more about `dev_mode()` ... I think it's really `load_all()` that has made it feel unnecessary. I think its original main use was probably for working with an in-development package and not wanting to necessary install that in-development version into one's main library. But now we just use `load_all()` for this sort of test-driving.

**Comment by jennybc** [comment]
In addition to `devtools::load_all()`, I think `devtools::test()` and `devtools::check()` are also part of the story.

**Pull request merged**
